sudo: required
dist: trusty

env:
  global:
    - SHYFT_DEPENDENCIES_DIR=$HOME/shyft-dependencies

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get --assume-yes install liblapack-dev g++-6 gcc-6 gfortran
  - export CXX="g++-6" CC="gcc-6"


cache:
  directories:
    - $SHYFT_DEPENDENCIES_DIR

language:
  - cpp

os:
  - linux

#python:
#  - 3.4

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - ulimit -s 32768  # C++ compilers require a lot of memory

  # Install conda (including fix for boost python build that do not recognize the m -letter variant)
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - ln -s $HOME/miniconda/include/python3.5m $HOME/miniconda/include/python3.5

  # Install dependencies (including fix for boost python build that do not recognize the m -letter variant)
  - conda create -n shyft_env  pyyaml numpy libgfortran netcdf4 gdal matplotlib requests nose coverage pip shapely pyproj 
  - source activate shyft_env
  - ln -s $HOME/miniconda/envs/shyft_env/include/python3.5m $HOME/miniconda/envs/shyft_env/include/python3.5
  - python -V

  # The data repository dependency
  - git clone --depth=50 --branch=master https://github.com/statkraft/shyft-data.git shyft-data
  - ln -s `pwd`/shyft-data ../shyft-data  # make it visible to the test suite of shyft

#compiler:
#  - gcc
#  - clang

before_script:
  - export CXX="g++-6" CC="gcc-6"
  - mkdir build
  - cd build
  - cmake ..

# the script also uses a fix using LD_PRELOAD to solve issue related to anaconda distro and libgfortran 4
script:
  - export CXX="g++-6" CC="gcc-6"
  - gcc --version
  - g++-5 --version
  - make -j 3 VERBOSE=1   CXX="g++-6" CC="gcc-6" # 3 paralel compiler processes can take up to 5 GB RAM!
  - export LD_LIBRARY_PATH=$SHYFT_DEPENDENCIES_DIR/local/lib
  - export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0:/usr/lib/x86_64-linux-gnu/libgfortran.so.3 
  - make test
  - make install
  - PYTHONPATH=.. python -c"import shyft; shyft.print_versions()"
  - nosetests ..

notifications:
  email: false
